esphome:
  name: scent-diffuser
  friendly_name: srakhrakhok

esp32:
  board: esp32dev
  framework:
    type: arduino

deep_sleep:  
  id: your_deep_sleep

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "yourAPIKeyhere"

ota:
  - platform: esphome
    password: "yourOTApassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Srakhrakhok Fallback Hotspot"
    password: "abcdefghi"

captive_portal:

globals:
  - id: daily_counter
    type: int
    restore_value: yes
    initial_value: '0'
  - id: total_counter
    type: int
    restore_value: yes
    initial_value: '0'

# number for sleep duration
number:
  - platform: template
    id: deep_sleep_duration
    name: "Deep Sleep Duration Minutes"
    optimistic: true
    min_value: 1
    max_value: 720
    step: 2

switch:
  - platform: gpio
    pin: GPIO15
    id: srakhrakhok
    inverted: yes
    name: "Srakhrakhok Spray"
    on_turn_on:
      - lambda: |-
          id(daily_counter) += 1;
          id(total_counter) += 1;
          ESP_LOGI("main", "Daily counter: %d, Total Counter: %d", id(daily_counter), id(total_counter));
      - delay: 2s
      - switch.turn_off: srakhrakhok
      - delay: 2s

  - platform: template
    name: "Reset Counters"
    id: reset_counters
    turn_on_action:
      - lambda: |-
          id(daily_counter) = 0;
          id(total_counter) = 0;
          ESP_LOGI("main", "Counters reset");

  # switch for deep sleep
  - platform: template
    name: "Srakhrakhok Deep Sleep"
    id: deep_sleep_switch
    turn_on_action:
      - delay: 1s  # Small delay to ensure the switch action is registered
      - lambda: |-
          // Read the number value for sleep duration
          int duration_in_minutes = int(id(deep_sleep_duration).state);
          ESP_LOGI("main", "Entering deep sleep for %d minutes", duration_in_minutes);
          id(your_deep_sleep).set_sleep_duration(duration_in_minutes*60*1000);
          id(your_deep_sleep).begin_sleep();

sensor:
  - platform: template
    name: "Daily Counter"
    lambda: |-
      return (float) id(daily_counter);
    icon: "mdi:counter"
    unit_of_measurement: "activations"
    accuracy_decimals: 0

  - platform: template
    name: "Total Counter"
    lambda: |-
      return (float) id(total_counter);
    icon: "mdi:counter"
    unit_of_measurement: "activations"
    accuracy_decimals: 0

  - platform: template
    name: "Percentage Spent"
    lambda: |-
      return (float) id(total_counter) / 1500.0 * 100.0;
    icon: "mdi:percent"
    unit_of_measurement: "%"
    accuracy_decimals: 1

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 59
        hours: 6
        then:
          - lambda: |-
              id(daily_counter) = 0;
              ESP_LOGI("main", "Daily counter reset at 06:59");
    
      - seconds: 10
        minutes: 58
        hours: 6
        then:
           lambda: |-
              ESP_LOGI("main", "Waking up from deep sleep at 06:58");

            
